### ISSUE TITLE
aria NG 连接不了

### ISSUE THREAD

**Issue by 66508393** [hmglife/aria2-colab#1]
用网页打开 ngrok 出现这个错误 The error encountered was: dial tcp 127.0.0.1:6800: connect: connection refused
是那里出问题了？

**Comment by hmglife** [comment]
用的免费token吗？尝试取消勾选free token，按照教程注册ngrok填入自己token测试

**Comment by 66508393** [comment]
免费与自已注册的 都是一样

Failed to complete tunnel connection
The connection to http://f561309d678d.jp.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:6800.

Make sure that a web service is running on localhost:6800 and that it is a valid address.

The error encountered was: dial tcp 127.0.0.1:6800: connect: connection refused

**Comment by 66508393** [comment]
Exception caught
Exception: [download_helper.cc:562] errorCode=1 Failed to open the file /root/.aria2/aria2.session, cause: File not found or it is a directory

你查一下 会有地方调用了  ./aria2c 这个文件夹的！

**Comment by hmglife** [comment]
试一试上面配置文件不填能否启动，我这边是正常的，如果不填启动了说明aria2配置有问题

**Comment by 66508393** [comment]
我把 ./aria2 cp 一份为 ./aria2c 现在正常了！

**Comment by hmglife** [comment]
已找到原因，提供的aria默认配置路径有误（默认为/.aria2），目前还是只能使用Linux环境跑一次脚本后保存或者修改配置里的文件目录到/.aria2c来解决,谢谢反馈。

**Comment by hmglife** [comment]
已更新脚本到V1.1，下载最新版即可。
