### ISSUE TITLE
colab脚本AriaNG连接失败

### ISSUE THREAD

**Issue by creazytom** [hmglife/aria2-colab#2]
用了自己的rclone.conf配置文件，参考了网站里面的配置，把script.conf里面的网盘名称改成和rclone.conf配置的name一样，把这三个文件的goindex-theme-acrou直链填上去，连接ariang失败，是配置文件里面还有哪些需要改吗，下载目录是不是也需要改成rclone.conf配置的团队盘路径？

**Comment by creazytom** [comment]
aria2.conf没有修改，直接用的项目下面默认的配置

**Comment by hmglife** [comment]
已解决问题，默认配置路经有误，稍等一下正在更新脚本，更新后下载最新版

**Comment by creazytom** [comment]
用了你刚刚上传的aria.conf现在已经连接上了

**Comment by hmglife** [comment]
已更新脚本到V1.1，下载最新版即可。

**Comment by creazytom** [comment]
这个添加磁力下载完成后，自动上传到网盘的哪个目录啊，没找到啊

**Comment by hmglife** [comment]
script已更新，之前是/Colab/Download，刚刚改回根目录了，不过不建议根目录。改了配置目录上传看不见尝试先在对应位置创建空目录，检查colab上文件是否还在，不在说明上传成功了

**Comment by creazytom** [comment]
只知道个人15g盘的目录是/root，如果想传到团队盘，目录该怎么写呢

**Comment by hmglife** [comment]
配置rclone时选了team drive 直接输入团队盘目录即可，如上传到团队盘文件夹Colab，测路经为/Colab 。

**Comment by creazytom** [comment]
在团队盘新建了一个目录并把script.conf的上传目录修改成了新建的目录，aria2下载完成之后，没有自动把文件传到对应的目录

**Comment by hmglife** [comment]
script里面路径要把注释复制下来，不要改成注释了，还不能解决只能再看看源作者的教程了。。。我这边没有问题的。。

**Comment by LIKE2000-ART** [comment]
那么能不能离线下载到挂载的Google Drive上来节约机器的空间呢（下载一个130G的软件

**Comment by hmglife** [comment]
> 那么能不能离线下载到挂载的Google Drive上来节约机器的空间呢（下载一个130G的软件

理论上可行，不过需要考虑aria2临时文件的反复更新是否会导致api的错误，可以自行挂载尝试，不过白嫖只能70G左右

**Comment by LIKE2000-ART** [comment]
> > 那么能不能离线下载到挂载的Google Drive上来节约机器的空间呢（下载一个130G的软件
> 
> 理论上可行，不过需要考虑aria2临时文件的反复更新是否会导致api的错误，可以自行挂载尝试，不过稳定白嫖只能70G左右

经过尝试，建议将aria2.conf中的下载完毕执行操作改为move.sh来达到此目的，直接下载至Google Drive会导致硬盘写入错误（尤其是团队盘），大文件最好的办法还是分次下载啊

**Comment by hmglife** [comment]
> > > 那么能不能离线下载到挂载的Google Drive上来节约机器的空间呢（下载一个130G的软件
> > 
> > 
> > 理论上可行，不过需要考虑aria2临时文件的反复更新是否会导致api的错误，可以自行挂载尝试，不过稳定白嫖只能70G左右
> 
> 经过尝试，建议将aria2.conf中的下载完毕执行操作改为move.sh来达到此目的，直接下载至Google Drive会导致硬盘写入错误（尤其是团队盘），大文件最好的办法还是分次下载啊

源作者的配置不在本脚本研究范围内，，可以自行修改相关参数，还是不建议直接往谷歌盘里下。
