### ISSUE TITLE
Ngrok 问题导致无法使用

### ISSUE THREAD

**Issue by Theotimus** [hmglife/aria2-colab#7]
The connection to http://a10ad6329e9a.jp.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:6800.

Make sure that a web service is running on localhost:6800 and that it is a valid address.

The error encountered was: dial tcp 127.0.0.1:6800: connect: connection refused

**Comment by hmglife** [comment]
已在问题置顶说明
