### ISSUE TITLE
脚本在Colab环境执行出现的一个问题导致了rpc连不上

### ISSUE THREAD

**Issue by hmglife** [hmglife/aria2-colab#8]
大概情况是，脚本一旦执行了重启，或者覆盖了配置文件，rpc就会出现认证失败或者直接连不上的情况，小白暂时还没找到解决办法，临时使用的方法是不使用上传功能只使用下载功能，注释这两行：
#!wget echo https://raw.githubusercontent.com/hmglife/aria2-colab/master/aria2.conf -O /root/.aria2c/aria2.conf &> /dev/null
#!echo 6|./aria2.sh &> /dev/null
如要用命令方式下载参考这条：
from google.colab import files
files.download("文件地址/文件名")

**Comment by hmglife** [comment]
大概情况是，脚本一旦执行了重启，或者覆盖了配置文件，rpc就会出现认证失败或者直接连不上的情况，小白暂时还没找到解决办法，临时使用的方法是不使用上传功能只使用下载功能，注释这两行：
#!wget echo https://raw.githubusercontent.com/hmglife/aria2-colab/master/aria2.conf -O /root/.aria2c/aria2.conf &> /dev/null
#!echo 6|./aria2.sh &> /dev/null
如要用命令方式下载参考这条：
from google.colab import files
files.download("文件地址/文件名")

**Comment by upupoo108** [comment]
前几天突然就这样了，好奇怪，是被谷歌发现了吗？

**Comment by upupoo108** [comment]
应该是ngrok出了问题

**Comment by LIKE2000-ART** [comment]
并且现在好像还会封禁colab,显示当前没有可用后端
